<%inherit file="_templates/site.mako" />
<div id="col_1">
	<h2>La maquina absurda - 2009</h2>
	<p>Project with workshop format done in colaboration with Chris Sugrue during SummerLab 2009<p>
	<p>During SummerLab 2009 we proposed the assistants to think in a piece of a Rude Goldberg machine.</p>
	<p>There were only a rule, each software based piece should be connected to a hardware one. And the first of the elements should be connected to the last one.</p>
    <p>Once the machine was connected each element began to trigger the next in and endless loop... Till one of them broke</p>
    <p>All the ideas for the elements of the machine were thought and created during the week. At the end there were a hairdryer inflating a trash bag triggering a proximity sensor, a little robot wandering around the space who was seen by a camera which produced sounds. A plastic cups telephone transmitting sound from one computer to another. A cloth line moved by motors activated by some software that was looking for a laser projected on a wall. Some particle system visuals generated by lentils jumping on a speaker. And several more.</p>
	<h3>software</h3>
	<p>Most of the pieces were developed using openFrameworks, Processing and Arduino</p>
</div>
<div id="col_2">
<object width="400" height="320"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=6688106&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=1&amp;color=ffffff&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=6688106&amp;server=vimeo.com&amp;show_title=1&amp;show_byline=1&amp;show_portrait=1&amp;color=ffffff&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="400" height="320"></embed></object><p><a href="http://vimeo.com/6688106">La máquina absurda / The absurd machine</a> from <a href="http://vimeo.com/zigazaga">Zz</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
</div>
